/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "RPCMessage_constants.h"



const RPCMessageConstants g_RPCMessage_constants;

RPCMessageConstants::RPCMessageConstants() {
}



