/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef RPCMessage_CONSTANTS_H
#define RPCMessage_CONSTANTS_H

#include "RPCMessage_types.h"



class RPCMessageConstants {
 public:
  RPCMessageConstants();

};

extern const RPCMessageConstants g_RPCMessage_constants;



#endif
